/*
 * Copyright (c) Cangjie Library Team 2022-2022. All rights resvered.
 */

/**
 * @file
 *
 */
package qt.gui

/**
 * The class is QPaintersEvent
 * @author wathinst
 */
public class QPaintersEvent{
    /* let member ptr type is Int64 */
    let ptr: Int64

    /**
     * The Function is init constructor
     *
     * @param ptr of Int64
     */
    public init(ptr: Int64) {
        this.ptr = ptr
    }
}