[dependencies]

[ffi]
  [ffi.c]
    nativeQt = {path = "./native/build"}

[package]
  cjc-version = "0.53.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "cjqt"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "0.2.0"
  package-configuration = {}
