/*
 * Copyright (c) Cangjie Library Team 2022-2022. All rights resvered.
 */

/**
 * @file
 *
 */
package cjqt.widgets

/**
 * The class is QGraphicsSceneContextMenuEvent
 * @author helin
 */
public class QGraphicsSceneContextMenuEvent<:QGraphicsSceneEvent{

    /**
     * The Function is init constructor
     *
     * @param ptr of Int64
     */
    public init(ptr: Int64) {
        super(ptr)
    }
}